apiVersion: v2
name: setve-cluster
description: Universal Simulation & Telemetry Validation Engine (SETVE) Helm Chart for Dedicated Bare-Metal Kubernetes
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - storage
  - benchmark
  - load-generation
  - nvme
  - telemetry
  - prometheus
home: https://github.com/seismael/setve-simulator
sources:
  - https://github.com/seismael/setve-simulator
maintainers:
  - name: SETVE Core Team
